"""Generate a PyInstaller --version-file from __version__ in jamo_fixer.py.

Writes version_info.txt next to this script. Run before `pyinstaller` so the
exe carries Windows file-property metadata (file/product version, name, etc).
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
source = (HERE / "jamo_fixer.py").read_text(encoding="utf-8")
m = re.search(r'__version__\s*=\s*"([^"]+)"', source)
if not m:
    sys.exit("__version__ not found in jamo_fixer.py")
version = m.group(1)
parts = [p for p in version.split(".") if p.isdigit()]
while len(parts) < 4:
    parts.append("0")
filevers = ", ".join(parts[:4])

content = f"""# Auto-generated by generate_version_info.py. Do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({filevers}),
    prodvers=({filevers}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [
          StringStruct(u'CompanyName', u'yujeong0411'),
          StringStruct(u'FileDescription', u'Jamo Fixer — Korean filename NFC fixer'),
          StringStruct(u'FileVersion', u'{version}'),
          StringStruct(u'InternalName', u'JamoFixer'),
          StringStruct(u'OriginalFilename', u'JamoFixer.exe'),
          StringStruct(u'ProductName', u'Jamo Fixer'),
          StringStruct(u'ProductVersion', u'{version}'),
        ])
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""

out = HERE / "version_info.txt"
out.write_text(content, encoding="utf-8")
print(f"Wrote {out.name} for version {version}")
